version: '3.8'
include:
  - path: ./docker-compose.yml
services:
  # -------------------- email -------------------------------#
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - '5000:80' # Port for accessing smtp4dev's web interface
      - '2525:25' # Port for SMTP connections
    restart: always
