services:
  postgres-veritable-ui:
    image: postgres:16.3-alpine
    container_name: postgres-veritable-ui
    ports:
      - 5432:5432
    volumes:
      - postgres-veritable-ui:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm

volumes:
  postgres-veritable-ui:
