services:
  # -------------------- shared -------------------------------#
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:release
    volumes:
      - ipfs:/data/ipfs

  # -------------------- alice -------------------------------#
  postgres-veritable-ui-alice:
    image: postgres:17.0-alpine
    container_name: postgres-veritable-ui-alice
    ports:
      - 5432:5432
    volumes:
      - postgres-veritable-ui-alice:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-alice:
    container_name: postgres-veritable-cloudagent-alice
    image: postgres:17.0-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-alice:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-alice:
    image: digicatapult/veritable-cloudagent
    container_name: veritable-cloudagent-alice
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3100:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-alice:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-alice
      - WALLET_ID=alice
      - WALLET_KEY=alice-key

  # -------------------- bob -------------------------------#
  veritable-ui-bob:
    container_name: veritable-ui-bob
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-veritable-ui-bob
      - veritable-cloudagent-bob
    ports:
      - 3001:3000
    command: >
      sh -c "
        npm i -g pino-colada
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-colada"
    env_file:
      - docker/test.env
      - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=trace
      - DB_HOST=postgres-veritable-ui-bob
      - DB_NAME=veritable-ui
      - API_SWAGGER_TITLE=Bob
      - API_SWAGGER_BG_COLOR=#ff3131
      - PUBLIC_URL=http://localhost:3001
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-bob:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-bob:3000
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - COOKIE_SESSION_KEYS=secret
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/veritable/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - INVITATION_FROM_COMPANY_NUMBER=07964699
      - INVITATION_PIN_SECRET=secret
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - DEMO_MODE=true
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=
      - SMTP_PORT=25
      - SMTP_USER=
  postgres-veritable-ui-bob:
    image: postgres:17.0-alpine
    container_name: postgres-veritable-ui-bob
    ports:
      - 5433:5432
    volumes:
      - postgres-veritable-ui-bob:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-bob:
    container_name: postgres-veritable-cloudagent-bob
    image: postgres:17.0-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-bob:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-bob:
    image: digicatapult/veritable-cloudagent
    container_name: veritable-cloudagent-bob
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3101:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-bob:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-bob
      - WALLET_ID=bob
      - WALLET_KEY=bob-key
      
  # -------------------- charlie -------------------------------#
  veritable-ui-charlie:
    container_name: veritable-ui-charlie
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-veritable-ui-charlie
      - veritable-cloudagent-charlie
    ports:
      - 3002:3000
    command: >
      sh -c "
        npm i -g pino-colada
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-colada"
    env_file:
      - docker/test.env
      - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=trace
      - DB_HOST=postgres-veritable-ui-charlie
      - DB_NAME=veritable-ui
      - API_SWAGGER_TITLE=charlie
      - API_SWAGGER_BG_COLOR=#ff3131
      - PUBLIC_URL=http://localhost:3002
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-charlie:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-charlie:3000
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - COOKIE_SESSION_KEYS=secret
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/veritable/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - INVITATION_FROM_COMPANY_NUMBER= -> 07964699
      - INVITATION_PIN_SECRET=secret
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - DEMO_MODE=true
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=
      - SMTP_PORT=25
      - SMTP_USER=
  postgres-veritable-ui-charlie:
    image: postgres:17.0-alpine
    container_name: postgres-veritable-ui-charlie
    ports:
      - 5434:5432
    volumes:
      - postgres-veritable-ui-charlie:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-charlie:
    container_name: postgres-veritable-cloudagent-charlie
    image: postgres:17.0-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-charlie:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-charlie:
    image: digicatapult/veritable-cloudagent
    container_name: veritable-cloudagent-charlie
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3102:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-charlie:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-charlie
      - WALLET_ID=charlie
      - WALLET_KEY=charlie-key

  # -------------------- email -------------------------------#
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - '5000:80' # Port for accessing smtp4dev's web interface
      - '2525:25' # Port for SMTP connections
    restart: always

volumes:
  ipfs:
  postgres-veritable-ui-alice:
  postgres-veritable-ui-bob:
  postgres-veritable-ui-charlie:
  postgres-veritable-cloudagent-alice:
  postgres-veritable-cloudagent-bob:
  postgres-veritable-cloudagent-charlie:
