include:
  - path: ./docker-compose.yml
    env_file:
      - ./docker/e2e.env
services:
  # -------------------- alice -------------------------------#
  veritable-ui-alice:
    container_name: veritable-ui-alice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-veritable-ui-alice
      - veritable-cloudagent-alice
    ports:
      - 3000:3000
    command: >
      sh -c "
        npm i -g pino-colada
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-colada"
    env_file:
      - docker/test.env
    # - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - DB_HOST=postgres-veritable-ui-alice
      - DB_NAME=veritable-ui
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - COOKIE_SESSION_KEYS=secret
      - PUBLIC_URL=${VERITABLE_ALICE_PUBLIC_URL:-http://localhost:3000}
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=${VERITABLE_IDP_PUBLIC_URL_PREFIX:-http://localhost:3080/realms/veritable/protocol/openid-connect}
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-alice:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-alice:3000
      - INVITATION_PIN_SECRET=secret
      - INVITATION_FROM_COMPANY_NUMBER=07964699
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=
      - SMTP_PORT=25
      - SMTP_USER=
      - EMAIL_TRANSPORT=SMTP_EMAIL
      - API_SWAGGER_TITLE=Alice
      - API_SWAGGER_BG_COLOR=#ff3131
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - DEMO_MODE=true
      - SMTP_SECURE=false
      - COMPANY_PROFILE_API_KEY=${VERITABLE_COMPANY_PROFILE_API_KEY:-COMPANY_PROFILE_API_KEY}
  # -------------------- email -------------------------------#
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - '5000:80' # Port for accessing smtp4dev's web interface
      - '2525:25' # Port for SMTP connections
    restart: always
