services:
  # -------------------- shared -------------------------------#
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:release
    volumes:
      - ipfs:/data/ipfs

  # -------------------- alice -------------------------------#
  veritable-ui-alice:
    container_name: veritable-ui-alice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres-veritable-ui-alice:
        condition: service_started
      veritable-cloudagent-alice:
        condition: service_healthy
    scale: 0
    ports:
      - 3000:3000
    command: >
      sh -c "
        npm i -g pino-pretty
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-pretty -c -l -o -s"
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - DB_HOST=postgres-veritable-ui-alice
      - DB_NAME=veritable-ui
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - COOKIE_SESSION_KEYS=secret
      - PUBLIC_URL=http://localhost:3000
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/veritable/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-alice:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-alice:3000
      - INVITATION_PIN_SECRET=secret
      - INVITATION_FROM_COMPANY_NUMBER=07964699
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=
      - SMTP_PORT=25
      - SMTP_USER=
      - EMAIL_TRANSPORT=SMTP_EMAIL
      - API_SWAGGER_TITLE=Alice
      - API_SWAGGER_BG_COLOR=#ff3131
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - DEMO_MODE=true
      - SMTP_SECURE=false
      - LOCAL_REGISTRY_TO_USE=GB
      - SOCRATA_API_URL=https://data.ny.gov/resource/p66s-i79p.json
      - COMPANY_PROFILE_API_KEY=${COMPANY_PROFILE_API_KEY}
  postgres-veritable-ui-alice:
    image: postgres:17.5-alpine
    container_name: postgres-veritable-ui-alice
    ports:
      - 5432:5432
    volumes:
      - postgres-veritable-ui-alice:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-alice:
    container_name: postgres-veritable-cloudagent-alice
    image: postgres:17.5-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-alice:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-alice:
    image: digicatapult/veritable-cloudagent:v0.13.22
    container_name: veritable-cloudagent-alice
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3100:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-alice:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-alice
      - WALLET_ID=alice
      - WALLET_KEY=alice-key

  # -------------------- bob -------------------------------#
  veritable-ui-bob:
    container_name: veritable-ui-bob
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres-veritable-ui-bob:
        condition: service_started
      veritable-cloudagent-bob:
        condition: service_healthy
    ports:
      - 3001:3000
    command: >
      sh -c "
        npm i -g pino-pretty
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-pretty -c -l -o -s"
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - DB_HOST=postgres-veritable-ui-bob
      - DB_NAME=veritable-ui
      - API_SWAGGER_TITLE=Bob
      - API_SWAGGER_BG_COLOR=#ff3131
      - PUBLIC_URL=http://localhost:3001
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-bob:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-bob:3000
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - COOKIE_SESSION_KEYS=secret
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/veritable/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - INVITATION_FROM_COMPANY_NUMBER=04659351
      - INVITATION_PIN_SECRET=secret
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - DEMO_MODE=true
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=password
      - SMTP_PORT=25
      - SMTP_USER=username
      - EMAIL_TRANSPORT=SMTP_EMAIL
      - SMTP_SECURE=false
      - LOCAL_REGISTRY_TO_USE=GB
      - SOCRATA_API_URL=https://data.ny.gov/resource/p66s-i79p.json
      - COMPANY_PROFILE_API_KEY=${COMPANY_PROFILE_API_KEY}

  postgres-veritable-ui-bob:
    image: postgres:17.5-alpine
    container_name: postgres-veritable-ui-bob
    ports:
      - 5433:5432
    volumes:
      - postgres-veritable-ui-bob:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-bob:
    container_name: postgres-veritable-cloudagent-bob
    image: postgres:17.5-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-bob:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-bob:
    image: digicatapult/veritable-cloudagent:v0.13.22
    container_name: veritable-cloudagent-bob
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3101:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-bob:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-bob
      - WALLET_ID=bob
      - WALLET_KEY=bob-key

  # -------------------- charlie -------------------------------#
  veritable-ui-charlie:
    container_name: veritable-ui-charlie
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres-veritable-ui-charlie:
        condition: service_started
      veritable-cloudagent-charlie:
        condition: service_healthy
    ports:
      - 3002:3000
    # env_file:
    #   - .env
    command: >
      sh -c "
        npm i -g pino-pretty
        node ./node_modules/.bin/knex migrate:latest
        npm start | pino-pretty -c -l -o -s"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - DB_HOST=postgres-veritable-ui-charlie
      - DB_NAME=veritable-ui
      - API_SWAGGER_TITLE=Charlie
      - API_SWAGGER_BG_COLOR=#ffbd59
      - PUBLIC_URL=http://localhost:3002
      - CLOUDAGENT_ADMIN_ORIGIN=http://veritable-cloudagent-charlie:3000
      - CLOUDAGENT_ADMIN_WS_ORIGIN=ws://veritable-cloudagent-charlie:3000
      - COMPANY_HOUSE_API_URL=https://api.company-information.service.gov.uk
      - COOKIE_SESSION_KEYS=secret
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - IDP_CLIENT_ID=veritable-ui
      - IDP_PUBLIC_URL_PREFIX=http://localhost:3080/realms/veritable/protocol/openid-connect
      - IDP_INTERNAL_URL_PREFIX=http://keycloak:8080/realms/veritable/protocol/openid-connect
      - INVITATION_PIN_SECRET=secret
      - INVITATION_FROM_COMPANY_NUMBER=10016023
      - ISSUANCE_DID_POLICY=EXISTING_OR_NEW
      - ISSUANCE_SCHEMA_POLICY=EXISTING_OR_NEW
      - ISSUANCE_CRED_DEF_POLICY=EXISTING_OR_NEW
      - DEMO_MODE=true
      - SMTP_HOST=smtp4dev
      - SMTP_PASS=password
      - SMTP_PORT=25
      - SMTP_USER=username
      - EMAIL_TRANSPORT=SMTP_EMAIL
      - SMTP_SECURE=false
      - COMPANY_PROFILE_API_KEY=${COMPANY_PROFILE_API_KEY}
      - LOCAL_REGISTRY_TO_USE=GB
      - SOCRATA_API_URL=https://data.ny.gov/resource/p66s-i79p.json

  postgres-veritable-ui-charlie:
    image: postgres:17.5-alpine
    container_name: postgres-veritable-ui-charlie
    ports:
      - 5434:5432
    volumes:
      - postgres-veritable-ui-charlie:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veritable-ui
  postgres-veritable-cloudagent-charlie:
    container_name: postgres-veritable-cloudagent-charlie
    image: postgres:17.5-alpine
    restart: on-failure
    volumes:
      - postgres-veritable-cloudagent-charlie:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
  veritable-cloudagent-charlie:
    image: digicatapult/veritable-cloudagent:v0.13.22
    container_name: veritable-cloudagent-charlie
    restart: always
    depends_on:
      ipfs:
        condition: service_healthy
    ports:
      - 3102:3000
    env_file:
      - docker/cloudagent.env
    environment:
      - ENDPOINT=ws://veritable-cloudagent-charlie:5003
      - POSTGRES_HOST=postgres-veritable-cloudagent-charlie
      - WALLET_ID=charlie
      - WALLET_KEY=charlie-key

  # -------------------- email -------------------------------#
  smtp4dev:
    image: rnwood/smtp4dev:3.8.6
    container_name: smtp4dev
    ports:
      - '5001:80' # Port for accessing smtp4dev's web interface
      - '2525:25' # Port for SMTP connections
    restart: always

  # -------------------- wiremock ----------------------------#

  wiremock-organisation-registries:
    image: wiremock/wiremock:3.13.1
    container_name: wiremock-organisation-registries
    scale: 0
    ports:
      - '8443:8080' # Port for accessing wiremock
    restart: always
    volumes:
      - ./test/wiremock/:/home/wiremock/mappings/

volumes:
  ipfs:
  postgres-veritable-ui-alice:
  postgres-veritable-ui-bob:
  postgres-veritable-ui-charlie:
  postgres-veritable-cloudagent-alice:
  postgres-veritable-cloudagent-bob:
  postgres-veritable-cloudagent-charlie:
